### ISSUE TITLE
Hot reload produces dispose error

### ISSUE THREAD

**Issue by emri99** [cedvdb/phone_form_field#11]
I've got this error on hot reload.
To reproduce, I think that performing hot reload while a country selector is opened should do the trick ;)

```
The following assertion was thrown while finalizing the widget tree:
A ValueNotifier<PhoneNumberInput?> was used after being disposed.

Once you have called dispose() on a ValueNotifier<PhoneNumberInput?>, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:212:12)
#3      _PhoneFormFieldState.dispose (package:phone_form_field/src/widgets/phone_form_field.dart:85:20)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4800:11)

```

I've solved it by changing in the dispose method of `phone_form_field.dart`:

```
  @override
  void dispose() {
    baseController.dispose();
    // dispose the controller only when it's initialised in this instance
    // otherwise this should be done where instance is created
    if (widget.controller == null) {
      controller.dispose();
    }
    super.dispose();
  }
```

Additionally, same problem may occurs on `base_phone_form_field.dart`, which can be prevent using same strategy:

```
@override
  void dispose() {
    _focusNode.dispose();
    _nationalController.dispose();
    _isoCodeController.dispose();
    // dispose the phoneController only when it's initialised in this
    // instance otherwise this should be done where instance is created
    if (widget.controller == null) {
      _phoneController.dispose();
    }
    super.dispose();
  }
```

I've already forked and fix this, although I don't have commit anything currently. I can propose you a PR for this issue.

By the way, I'm currently working on adding few others fix/features/customisations like a new `CountrySelectorNavigator` too. If you want to talk about, we can reach each other (not sure it's the right place here) to discuss ;)

**Comment by emri99** [comment]
Does the tests was green before ? Even after stashing my changes, it keeps
failing, did I miss something ?
